# Generated by Django 4.1.8 on 2023-07-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=155)),
                ('description', models.TextField()),
                ('picture', models.URLField(blank=True, max_length=155)),
                ('website', models.URLField(blank=True, max_length=155)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
