# Generated by Django 4.1.8 on 2023-07-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_workexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='saved_experiences',
            field=models.ManyToManyField(blank=True, to='api.workexperience'),
        ),
    ]
