# Generated by Django 4.1.8 on 2023-08-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_workshop_userprofile_saved_workshops'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='saves',
            field=models.IntegerField(default=0),
        ),
    ]
