# Generated by Django 4.1.8 on 2023-08-04 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_workshop_saves'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='ceated_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='ceated_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='ceated_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='workexperience',
            old_name='ceated_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='workshop',
            old_name='ceated_at',
            new_name='created_at',
        ),
    ]
