# Generated by Django 4.1.8 on 2023-08-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_ceated_at_company_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.CharField(blank=True, choices=[('LT1', 'Less than 1 year'), ('B12', 'Between 1 and 2 years'), ('B26', 'Between 2 and 6 years'), ('GT6', 'Greater than 6 years')], default='B12', max_length=3),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, choices=[('Full-time', 'Full Time'), ('Part-time', 'Part Time'), ('Internship', 'Internship'), ('Freelance', 'Freelance'), ('Other', 'Other')], default='Full-time', max_length=10),
        ),
    ]
